sudo: required
language: python
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get -t trusty-backports install -qq lxc
install:
  - export lxc_attach="sudo lxc-attach --clear-env -n mlr"
  - export mlr="cd /opt/mailur && . env/bin/activate && mlr"
  - sudo sh -c "no_login=1 ./bin/lxc"
  - echo "cd /opt/mailur && bin/install-test" | $lxc_attach
script:
  - echo "$mlr lint --ci" | $lxc_attach
  - echo "$mlr test" | $lxc_attach
  - echo "cd /opt/mailur && yarn run build" | $lxc_attach
